### ISSUE TITLE
Create Dev Branch

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/raven_front#12]
**Prerequisites**
 - [x] Did you perform a cursory search?
 - [x] Are you running the latest version?

**Is your feature request related to a problem? Please describe.**
As an organised person, I want moontree to follow the development flow as described in the Wiki.

**Describe the solution you'd like**
Create a development branch as the default branch for this repo.

**Comment by Brock-Wood** [comment]
@canadaduane @lastmeta I'm going to create a dev branch on each repo. This may cause issues with your local environments when you go to pull.

**Comment by lastmeta** [comment]
we'll want to set our upstream to dev before pushing `git push --set-upstream origin dev`
and set our local branches to dev

**Comment by Brock-Wood** [comment]
@lastmeta @canadaduane 

I changed a couple of other things. 

Everyone should:
1. Locally re-clone each repo. 
2. Copy/Pasta .env file to newly cloned repo(s) as needed.

Here's a list of all of the commands to run for re-cloning:
```bash
git clone git@github.com:moontreeapp/raven_front.git

git clone git@github.com:moontreeapp/raven_back.git

git clone git@github.com:moontreeapp/raven_server.git

git clone git@github.com:moontreeapp/ravencoin_wallet.git

git clone git@github.com:moontreeapp/raven_electrum.git

git clone git@github.com:moontreeapp/reservoir.git

git clone git@github.com:moontreeapp/raven_landing.git

git clone git@github.com:moontreeapp/landing_RVN.git
```
