### ISSUE TITLE
Loading Screen Hang

### ISSUE THREAD

**Issue by Brock-Wood** [moontreeapp/raven_front#38]
**Prerequisites**
 - [x] Did you perform a cursory search?
 - [x] Are you running the latest version?

**Describe the bug**
The loading screen hangs on app startup.

**To Reproduce**
1. Run App
2. See error

**Expected behavior**
When the app loads it should show the loading screen and then the home screen.

**Screenshots**
https://user-images.githubusercontent.com/9276931/144446582-c4f15a09-097c-4701-9cf8-7ce145acfd14.mp4

**Smartphone (please complete the following information):**
 - Device: Note 20 Ultra
 - OS: Android

**Comment by lastmeta** [comment]
I have seen this, but am unable to reproduce the issue.

**Comment by lastmeta** [comment]
I saw this again today, wiping the emulator fixes it. not sure if its due to datadog or database issue

**Comment by lastmeta** [comment]
with more experimentation I believe this has nothing to do with the database, but might have something to do with the ipfs pull/save or an integration like datadog

**Comment by lastmeta** [comment]
I've restarted several times when not dealing with ipfs, so the issue doesn't live in datadog

**Comment by lastmeta** [comment]
actaully, strike that last comment. I just ran it without ipfs functionality and it's cycling
