### ISSUE TITLE
Send screen validate address

### ISSUE THREAD

**Issue by lastmeta** [moontreeapp/raven_front#76]
### Describe The Bug

Use the UI validator to verify its a valid address

### To Reproduce

put in an invalid address, no validation on change

### Expected Behavior

red if not valid, green if valid

**Comment by canadaduane** [comment]
We can use raven_back `bs58check` library to check that the address is valid instead of regex

**Comment by lastmeta** [comment]
87cbad95bc03b476e325a9466e50d1f229142a19
